server:
  port: 8092
spring:
  application:
    name: cards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5424}/${DB_NAME:cards}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8071/}"
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        missing-queues-fatal: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: ERROR
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: ERROR



management:
  endpoints:
    web:
      exposure:
        include: "*"
#  docker:
#    compose:
#      lifecycle-management: start_only
#      file: compose.yml