services:
  accounts-db:
    image: 'postgres:18-alpine'
    container_name: accounts-db
    environment:
      POSTGRES_DB: accounts
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5423:5432'
    volumes:
      - accounts-pg-volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d accounts" ]
      start_period: 30s
    extends:
      file: ../common-docker-config.yml
      service: microservice-base

  accounts-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounts-api
    ports:
      - '8091:8091'
    environment:
      DB_HOST: accounts-db
      DB_PORT: 5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db:5432/accounts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OTEL_SERVICE_NAME: accounts
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    depends_on:
      accounts-db:
        condition: service_healthy
    extends:
      file: ../common-docker-config.yml
      service: microservice-with-config-eureka

volumes:
  accounts-pg-volume:
