services:
  accounts-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounts-api
    ports:
      - '8091:8091'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db:5432/accounts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OTEL_SERVICE_NAME: accounts
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    depends_on:
      accounts-db:
        condition: service_healthy
    extends:
      file: ../common-docker-config.yml
      service: microservice-with-config-eureka
