services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - '8070:8070'
    environment:
      CONFIG_SERVER_URL: http://config-server:8071/
      OTEL_SERVICE_NAME: eureka-server
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8070/actuator/health/readiness || exit 1" ]
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    extends:
      file: ../common-docker-config.yml
      service: microservice-with-config-server
    depends_on:
      config-server:
        condition: service_healthy
