services:
  shared-network:
    networks:
      - securedbank
  microservices-base:
    extends:
      service: shared-network
    deploy:
      resources:
        limits:
          memory: 700m
  microservice-with-config-server:
    extends: 
      service: microservices-base
    environment:
      CONFIG_SERVER_URL: configserver:http://config-server:8071
      EUREKA_DEFAULT_ZONE: http://eureka-server:8070/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      
