services:
  bank-db:
    image: 'postgres:18-alpine'
    container_name: bank-db
    environment:
      POSTGRES_DB: bank
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5423:5432'
    volumes:
      - bank-pg-volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bank" ]
      start_period: 30s
    extends:
      file: common-docker-config.yml
      service: microservice-base
