services:
  rabbitmq:
    image: rabbitmq:4.3.5-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    extends:
      file: common-docker-config.yml
      service: microservice-base

volumes:
  rabbitmq-data:
    driver: local

networks:
  securedbank:
    driver: bridge    