server:
  port: 8093

spring:
  application:
    name: loans
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5425}/${DB_NAME:loans}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8071/}"

logging:
  level:
    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: ERROR
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: ERROR



management:
  endpoints:
    web:
      exposure:
        include: "*"
