services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - '8071:8071'
    environment:
      OTEL_SERVICE_NAME: config-server
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8071/actuator/health/readiness || exit 1" ]
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    extends:
      file: ../docker/common.yml
      service: microservice-base