services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - '8071:8071'
    depends_on:
      rabbit-mq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - config-server
networks:
  config-server:
    driver: bridge