services:
  cards-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cards-api
    ports:
      - '8092:8092'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cards-db:5432/cards
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OTEL_SERVICE_NAME: cards
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    depends_on:
      cards-db:
        condition: service_healthy
    extends:
      file: ../common-docker-config.yml
      service: microservice-with-config-eureka
