services:
  cards-db:
    image: 'postgres:18-alpine'
    container_name: cards-db
    environment:
      POSTGRES_DB: cards
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5424:5432'
    volumes:
      - cards-pg-volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cards" ]
      start_period: 30s
    extends:
      file: ../common-docker-config.yml
      service: microservice-base

  cards-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cards-api
    ports:
      - '8092:8092'
    environment:
      DB_HOST: cards-db
      DB_PORT: 5432
      SPRING_DATASOURCE_URL: jdbc:postgresql://cards-db:5432/cards
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OTEL_SERVICE_NAME: cards
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    depends_on:
      cards-db:
        condition: service_healthy
    extends:
      file: ../common-docker-config.yml
      service: microservice-with-config-eureka

volumes:
  cards-pg-volume:
