services:
  loans-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loans-api
    ports:
      - '8093:8093'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank-db:5432/bank?currentSchema=loans
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OTEL_SERVICE_NAME: loans
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    depends_on:
      bank-db:
        condition: service_healthy
    extends:
      file: ../common-docker-config.yml
      service: microservice-with-config-eureka
