services:
  loans-db:
    image: 'postgres:18-alpine'
    container_name: loans-db
    environment:
      POSTGRES_DB: loans
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5425:5432'
    volumes:
      - loans-pg-volume:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d loans" ]
      start_period: 30s
    extends:
      file: ../common-docker-config.yml
      service: microservice-base

  loans-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loans-api
    ports:
      - '8093:8093'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://loans-db:5432/loans
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OTEL_SERVICE_NAME: loans
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    depends_on:
      loans-db:
        condition: service_healthy
    extends:
      file: ../common-docker-config.yml
      service: microservice-with-config-eureka

volumes:
  loans-pg-volume:
