apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: baicham/securedbank-config-server:s18
        ports:
        - containerPort: 8071
        env:

        - name: JAVA_TOOL_OPTIONS
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: JAVA_TOOL_OPTIONS
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: OTEL_EXPORTER_OTLP_PROTOCOL
        - name: OTEL_METRICS_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: OTEL_METRICS_EXPORTER
        - name: OTEL_LOGS_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: OTEL_LOGS_EXPORTER
        - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_1_0_ENABLED
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_1_0_ENABLED
        - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_2_0_ENABLED
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_2_0_ENABLED
        - name: OTEL_SERVICE_NAME
          value: "config-server"

        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "500m"
            memory: "700Mi"
