apiVersion: v2
name: securedbank
description: SecuredBank microservices umbrella chart (no Bitnami; Keycloak via codecentric/keycloakx)
type: application
version: 0.1.0
appVersion: "s15"
dependencies:
  - name: securedbank-lib
    version: 0.1.0
    repository: "file://charts/securedbank-lib"
  - name: keycloakx
    version: "7.2.2"
    repository: "https://codecentric.github.io/helm-charts"
    alias: keycloak
    condition: keycloak.enabled
