include:
  - docker/compose.dbs.yml
  - docker/compose.event.yml
  - docker/compose.observability.yml
  - config-server/compose.yml
  - eureka-server/compose.yml
  - accounts/compose.yml
  - cards/compose.yml
  - loans/compose.yml
  - message/compose.yml
  - gateway-server/compose.yml

volumes:
  accounts-pg-volume:
  cards-pg-volume:
  loans-pg-volume:

networks:
  securedbank:
    driver: bridge
