CREATE SCHEMA IF NOT EXISTS loans;

CREATE TABLE IF NOT EXISTS loans.loans (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_number VARCHAR(15) NOT NULL,
    loan_number VARCHAR(100) NOT NULL,
    loan_type VARCHAR(100) NOT NULL,
    total_loan INTEGER NOT NULL,
    amount_paid INTEGER NOT NULL,
    outstanding_amount INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP,
    updated_by VARCHAR(20)
);
