apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071 # exposed port
      targetPort: 8071 # container port