services:
  message:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message
    environment:
      KAFKA_BROKER: kafka:9092
      OTEL_SERVICE_NAME: message
    depends_on:
      kafka:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./build.gradle
    extends:
      file: ../common-docker-config.yml
      service: microservice-base
