apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:18-alpine
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h cards-db -p 5432 -U postgres -d cards; do
                echo "waiting for cards-db..."
                sleep 2
              done
      containers:
      - name: cards
        image: baicham/securedbank-cards-api:s15
        ports:
        - containerPort: 8092
        env:
        - name: SPRING_APPLICATION_NAME
          value: "cards"
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: CONFIG_SERVER_URL
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_DEFAULT_ZONE
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: EUREKA_DEFAULT_ZONE
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: securedbank-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://cards-db:5432/cards"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits:
            cpu: "500m"
            memory: "700Mi"
