server:
  port: 8070
spring:
  application:
    name: eureka-server
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8071/}"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8070/eureka/}
