server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active:
      - git # for git config server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cham207388/config-server-sb-sc-ms.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
#encrypt:
#  key: "SJEHQO2EUQWIENWAKJDHQO2I"
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id}]"
