CREATE TABLE IF NOT EXISTS customer (
   customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL,
   mobile_number VARCHAR(20) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_by VARCHAR(20) NOT NULL,
   updated_at TIMESTAMP,
   updated_by VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS accounts (
   customer_id INTEGER NOT NULL REFERENCES customer (customer_id),
   account_number BIGINT PRIMARY KEY,
   account_type VARCHAR(100) NOT NULL,
   branch_address VARCHAR(200) NOT NULL,
   balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
   communication_sw BOOLEAN,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_by VARCHAR(20) NOT NULL,
   updated_at TIMESTAMP,
   updated_by VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS transactions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   account_number BIGINT NOT NULL REFERENCES accounts (account_number),
   type VARCHAR(32) NOT NULL,
   amount NUMERIC(19, 2) NOT NULL,
   balance_after NUMERIC(19, 2) NOT NULL,
   counterparty_account BIGINT,
   description VARCHAR(255),
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_by VARCHAR(20) NOT NULL,
   updated_at TIMESTAMP,
   updated_by VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS idx_transactions_account_number ON transactions (account_number);
