CREATE SCHEMA IF NOT EXISTS accounts;

CREATE TABLE IF NOT EXISTS accounts.customer (
   customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL,
   mobile_number VARCHAR(20) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_by VARCHAR(20) NOT NULL,
   updated_at TIMESTAMP,
   updated_by VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS accounts.accounts (
   customer_id INTEGER NOT NULL REFERENCES accounts.customer (customer_id),
   account_number INTEGER PRIMARY KEY,
   account_type VARCHAR(100) NOT NULL,
   branch_address VARCHAR(200) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   created_by VARCHAR(20) NOT NULL,
   updated_at TIMESTAMP,
   updated_by VARCHAR(20)
);
